language: python
python:
  - "3.6"
before_script:
  - python -m unittest discover --start-directory roundrobin/tests
script:
  - roundrobin/assignment.py --seed ${HOLIDAY_SEED} --slots ${HOLIDAY_SLOTS} --format=english --log-level=${HOLIDAY_LOG_LEVEL} -- ${HOLIDAY_GIVERS} 
